name: Build
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"
  pull_request:
    branches:
      - "**"
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        node: [12, 14, 16]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install ImageMagick
        run: sudo apt install libmagick++-dev

      - name: Install dependencies and build 
        run: npm install

  build_musl:
    name: Build (musl)
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}-alpine
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - name: Setup env with Node v${{ matrix.node }}
        run: |
          apk add --update
          apk add --no-cache ca-certificates git curl build-base python3 g++ make imagemagick6-dev
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: npm install