name: CI
on:
  push:
    branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: sudo apt-get install libmagick++-dev
      - run: yarn
      - run: yarn install